let autoGeneratedOrderId = 1;
$('#txtOrderID').val('0-00'+autoGeneratedOrderId);


/* Load All Items to Table */

function loadAllOrderDetails() {

    /* This Removes table row Repeats */
    $('#orderTblBody').empty();

    for (let oDetails of orderDetails){
        let orderRow= `<tr>
                        <td>${oDetails.iCode}</td>
                        <td>${oDetails.itemName}</td>
                        <td>${oDetails.price}</td>
                        <td>${oDetails.Qty}</td>
                        <td>${oDetails.total}</td>
                       </tr>`;
        $('#orderTblBody').append(orderRow);
    }
}